name: Verificar Claims OIDC

on:
  workflow_dispatch:

jobs:
  verify-claims:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Permiso necesario para obtener el token OIDC
      contents: read

    steps:
      - name: Obtener Token OIDC
        id: token
        run: |
          echo "Obteniendo token OIDC..."
          curl -s -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" "$ACTIONS_ID_TOKEN_REQUEST_URL"

      - name: Mostrar Claims
        run: |
          echo "Claims obtenidos"
